### ISSUE TITLE
再生後しばらくすると シークバー更新がされなくなる。

### ISSUE THREAD

**Issue by sakkuntyo** [sakkuntyo/discord-sktrythmjs2#1]
Invalid Webhook Token が起きる

**Comment by sakkuntyo** [comment]
DiscordAPIError[50027]: Invalid Webhook Token$
114322     at handleErrors (C:\Users\noma3\discord-sktrythmjs2\node_modules\@discordjs\rest\dist\index.js:640:13)$
114323     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)$
114324     at async SequentialHandler.runRequest (C:\Users\noma3\discord-sktrythmjs2\node_modules\@discordjs\rest\dist\index.js:1021:23)$
114325     at async SequentialHandler.queueRequest (C:\Users\noma3\discord-sktrythmjs2\node_modules\@discordjs\rest\dist\index.js:862:14)$
114326     at async REST.request (C:\Users\noma3\discord-sktrythmjs2\node_modules\@discordjs\rest\dist\index.js:1387:22)$
114327     at async InteractionWebhook.editMessage (C:\Users\noma3\discord-sktrythmjs2\node_modules\discord.js\src\structures\Webhook.js:338:15)$
114328     at async ChatInputCommandInteraction.editReply (C:\Users\noma3\discord-sktrythmjs2\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:158:17) {$
114329   requestBody: {$
114330     files: [],$
114331     json: {$
114332       content: 'Author: BUMP OF CHICKEN\n' +$
114333         'Title: BUMP OF CHICKEN縲瑚ｨ伜ｿｵ謦ｮ蠖ｱ縲阪Μ繝ｪ繝・け繝薙ョ繧ｪ\n' +$
114334         'Url: <https://www.youtube.com/watch?v=FPLxRe4ho_A>\n' +$
114335         'RepeatMode: QUEUE\n' +$
114336         '03:23 笏・笆ｬ笆ｬ笆ｬ笆ｬ笆ｬ笆ｬ笆ｬ曝笆ｬ笆ｬ笆ｬ 笏・04:50',$
114337       tts: false,$
114338       nonce: undefined,$
114339       embeds: undefined,$
114340       components: undefined,$
114341       username: undefined,$
114342       avatar_url: undefined,$
114343       allowed_mentions: undefined,$
114344       flags: undefined,$
114345       message_reference: undefined,$
114346       attachments: undefined,$
114347       sticker_ids: undefined,$
114348       thread_name: undefined$
114349     }$
114350   },$
114351   rawError: { message: 'Invalid Webhook Token', code: 50027 },$
114352   code: 50027,$
114353   status: 401,$
114354   method: 'PATCH',$
114355   url: 'https://discord.com/api/v10/webhooks/1097470836711100446/aW50ZXJhY3Rpb246MTA5ODQzODE5OTIwMzg2MDU1NDpGbWt2V1FSWmZKTVA3WVFzd1VxaThFQkpvQTU3bzk1c3phWUpjeFAwcVhrR0lpemZRRUd2dzBiSFg5N2VJT2VLMUlVbUxDaUp6TmtKclg4d01Oa2Q3MW14UTU1eT       l1SFRlbXJkaEE2ZzRwTXFZTVhIaXVaTTZOU2xVSTU3VnlVNQ/messages/@original'$
114356 }

**Comment by sakkuntyo** [comment]
https://stackoverflow.com/questions/69218453/discord-js-slash-command-invalid-webhook-token-after-15-mins

**Comment by sakkuntyo** [comment]
https://github.com/sakkuntyo/discord-sktrythmjs2/commit/e946da68e6c8c7ec039ef352d22eaedfb2b7acb7 で修正されたはず！経過観察

**Comment by sakkuntyo** [comment]
> [e946da6](https://github.com/sakkuntyo/discord-sktrythmjs2/commit/e946da68e6c8c7ec039ef352d22eaedfb2b7acb7) で修正されたはず！経過観察

これは解決したけど----開始中----が/playするたびにでる

**Comment by sakkuntyo** [comment]
https://github.com/sakkuntyo/discord-sktrythmjs2/commit/0c9cee6659bacc23dd94ce365370d1f61b7ad0b0で解決
